---
# yaml-language-server: $schema=https://schema.blue-build.org/module-stage-list-v1.json

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  # put configuration files you want in /usr/etc/ inside the image
  # while putting files in /etc/ is done on booted system by system administrators.
  # read more about this in files module reference.

  - type: bling
    install:
      - rpmfusion

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - ddcutil
      - fish
      - tailscale
      #- zerotier-one
      - tlp
      - tlp-rdw
      - gnome-console
      - nautilus-gsconnect
      - openssh-askpass
      - gnome-backgrounds-extras
      - podman-compose
      - sushi
    remove:
      - firefox
      - firefox-langpacks
      - gnome-tweaks
      - gnome-classic-session

  - type: brew
    brew-analytics: false

  - type: fonts
    fonts:
      nerd-fonts:
        - IntelOneMono
        - GeistMono
        - JetBrainsMono
        - FiraCode
        - NerdFontsSymbolsOnly
      google-fonts:
        - Inter

  - type: gschema-overrides
    include:
      - zz1-default.gschema.override

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub-system
      repo-title: "Flathub (System)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.clocks
        - org.gnome.Connections
        - org.gnome.Contacts
        - org.gnome.Decibels # incubator app
        - org.gnome.Epiphany
        - org.gnome.font-viewer
        - org.gnome.Loupe
        - org.gnome.Maps
        - org.gnome.Music
        - org.gnome.NautilusPreviewer
        - org.gnome.Papers # incubator app
        - org.gnome.Showtime # incubator app
        - org.gnome.SimpleScan
        - org.gnome.SoundRecorder
        - org.gnome.Snapshot
        - org.gnome.TextEditor
        - org.gnome.Weather
        - org.mozilla.firefox
        - org.gnome.baobab
        ## Advanced tools:
        - app.devsuite.Ptyxis
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - org.gnome.Logs
        - io.missioncenter.MissionCenter
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
        - org.gnome.eog
        - org.gnome.Totem
        - org.gnome.Evince
        - com.visualstudio.code
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub-user
      repo-title: "Flathub"
      install:
        - com.visualstudio.code
        - com.visualstudio.code.tool.fish
        - com.visualstudio.code.tool.podman
