# image will be published to ghcr.io/<user>/<name>
name: os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  # put configuration files you want in /usr/etc/ inside the image
  # while putting files in /etc/ is done on booted system by system administrators.
  # read more about this in files module reference.

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/atim/zerotier-one/repo/fedora-%OS_VERSION%/atim-zerotier-one-fedora-%OS_VERSION%.repo
    install:
      - ddcutil
      - fish
      - tailscale
      - zerotier-one
      - tlp
      - tlp-rdw
      - gnome-console
      - nautilus-gsconnect
      - openssh-askpass
      - gnome-backgrounds-extras
    remove:
      - firefox
      - firefox-langpacks
      - gnome-tweaks
      - gnome-classic-session

  - type: akmods
    base: main # if not specified, classic "main" base is used by default
    install:
      - openrazer
      - rtl8814au
      - rtl88xxau

  - type: gnome-extensions
    install:
      - 5425 # Battery time
      - 6670 # Bluetooth Battery Meter
      - 779 # Clipboard Indicator
      - 307 # Dash to Dock
      - 6242 # Emoji Copy
      # - 6072 # Fullscreen to Empty Workspace
      - 5410 # Grand Theft Focus
      - 4805 # Panel corners
      # - 5446 # [QSTweak] Quick Setting Tweaker      - Rounded Window Corners Reborn
      - 6139 # Tailscale QS
      - 7065 # Tiling Shell
      - 7048 # Rounded Window Corners Reborn

  - type: brew
    packages:
      - bat
      - catimg
      - eza
      - git-delta
      - gh
      - micro
      - volta
      - pfetch
      - tldr
      - starship
      - glow
    brew-analytics: false

  - type: fonts
    fonts:
      nerd-fonts:
        - IntelOneMono
        - GeistMono
        - JetBrainsMono
        - FiraCode
        - NerdFontsSymbolsOnly
      google-fonts:
        - Inter

  - type: gschema-overrides
    include:
      - zz1-default.gschema.override

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub-system
      repo-title: "Flathub (System)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.gnome.baobab
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.clocks
        - org.gnome.Connections
        - org.gnome.Contacts
        # - org.gnome.Evince
        - org.gnome.Papers
        - org.gnome.font-viewer
        - org.gnome.Loupe
        - org.gnome.Maps
        - org.gnome.Music
        - org.gnome.NautilusPreviewer
        - org.gnome.Snapshot
        - org.gnome.SoundRecorder
        - org.gnome.SimpleScan
        - org.gnome.TextEditor
        - org.gnome.Weather
        - org.gnome.Epiphany
        - org.gnome.Decibels
        # - org.gnome.Totem
        - org.gnome.Showtime
        - org.mozilla.firefox
        ## Advanced tools:
        - app.devsuite.Ptyxis
        - com.github.tchx84.Flatseal
        - com.mattjakeman.ExtensionManager
        - org.gnome.Logs
        - io.missioncenter.MissionCenter
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
        - org.gnome.eog
        - org.gnome.Totem
        - org.gnome.Evince
        - com.visualstudio.code
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub-user
      repo-title: "Flathub"
      install:
        - com.visualstudio.code
        - com.visualstudio.code.tool.fish
        - com.visualstudio.code.tool.podman

  - type: bling
    install:
      - ublue-update # https://github.com/ublue-os/ublue-update

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
